# Utiliser l'image de base officielle pour Python
FROM python:3.9-slim

# Définir le répertoire de travail
WORKDIR .

# Copier les fichiers de requirements.txt et installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code de l'application
COPY . .

# Exposer le port 8000
EXPOSE 8000

# Commande pour lancer l'application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
